# ─────────────────────────────────────────────
# ▶︎  Playwright CI ◀︎
# One clean test run after every merge to main
# ─────────────────────────────────────────────
name: Playwright CI            # Label shown in Actions UI & README badge

# ────────────────
# Triggers
# ────────────────
on:
  push:                        # Run only when commits land on main
    branches: [main]

  # pull_request:              # 🔒 Disabled to avoid duplicate runs.
  #   branches: [main]         #   → Uncomment if you want pre‑merge checks.

# ────────────────
# Jobs
# ────────────────
jobs:
  test:                        # Single job for the entire suite
    runs-on: ubuntu-latest     # Fresh Linux VM each time

    # Environment variables (secrets are masked as *** in logs)
    env:
      TEST_USER: ${{ secrets.TEST_USER }}
      TEST_PASS: ${{ secrets.TEST_PASS }}
      BASE_URL:  ${{ secrets.BASE_URL }}

    steps:
      # 1️⃣  Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣  Set up Node.js (with npm cache)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣  Install dependencies + Playwright browsers
      - name: Install deps & browsers
        run: |
          npm ci
          npx playwright install --with-deps

      # 4️⃣  Run the Playwright test suite
      - name: Run Playwright tests
        run: npx playwright test --reporter=html     # Generates /playwright-report

      # 5️⃣  Upload the HTML report even if tests fail
      - name: Upload Playwright report
        if: always()                                 # Always run, even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report